In [1]:
import torch
from src.model import grad_first_model, first_model

In [2]:
xvals = torch.linspace(0.0, 2.0, 25)
params = torch.tensor([-1.0, 4.0])

In [6]:
first_model(params, xvals)

tensor([0.0000, 0.3264, 0.6389, 0.9375, 1.2222, 1.4931, 1.7500, 1.9931, 2.2222,
        2.4375, 2.6389, 2.8264, 3.0000, 3.1597, 3.3056, 3.4375, 3.5556, 3.6597,
        3.7500, 3.8264, 3.8889, 3.9375, 3.9722, 3.9931, 4.0000])

In [4]:
# mean = list()
# grad = list()

# for x in xvals:
#     mu, g = grad_first_model(params, x)
#     mean.append(mu)
#     grad.append(g)
    
# mean = torch.FloatTensor(mean)
# grad = torch.vstack(grad)

In [5]:
grad_first_model(params, xvals)

(tensor([0.0000, 0.3264, 0.6389, 0.9375, 1.2222, 1.4931, 1.7500, 1.9931, 2.2222,
         2.4375, 2.6389, 2.8264, 3.0000, 3.1597, 3.3056, 3.4375, 3.5556, 3.6597,
         3.7500, 3.8264, 3.8889, 3.9375, 3.9722, 3.9931, 4.0000]),
 tensor([[0.0000, 0.0000],
         [0.0069, 0.0833],
         [0.0278, 0.1667],
         [0.0625, 0.2500],
         [0.1111, 0.3333],
         [0.1736, 0.4167],
         [0.2500, 0.5000],
         [0.3403, 0.5833],
         [0.4444, 0.6667],
         [0.5625, 0.7500],
         [0.6944, 0.8333],
         [0.8403, 0.9167],
         [1.0000, 1.0000],
         [1.1736, 1.0833],
         [1.3611, 1.1667],
         [1.5625, 1.2500],
         [1.7778, 1.3333],
         [2.0069, 1.4167],
         [2.2500, 1.5000],
         [2.5069, 1.5833],
         [2.7778, 1.6667],
         [3.0625, 1.7500],
         [3.3611, 1.8333],
         [3.6736, 1.9167],
         [4.0000, 2.0000]]))